window.gicsIndustryData = {
            "Automobiles & Components": ["APTV", "BWA", "CAAS", "F", "GM", "HMC", "HOG", "LCII", "TM", "TSLA"],
            "Banks": ["BAC", "BCS", "C", "GBCI", "JPM", "KEY", "MTB", "ONB", "OZK", "PNC", "RF", "WFC"],
            "Capital Goods": ["BA", "BECN", "CAT", "CYD", "DE", "GD", "GE", "LMT", "MIDD", "NOC", "PCAR", "PLOW", "ROCK", "RTX", "SNA", "TREX", "TWI", "WNC"],
            "Commercial Services & Supplies": ["ASGN", "FCN", "RBA", "VRSK"],
            "Consumer Durables & Apparel": ["GRMN", "HAS", "LULU", "MAT", "MOV", "NKE", "PTON", "SONY", "SWBI", "UAA", "VFC", "VRA"],
            "Consumer Services": ["CAKE", "CMG", "CZR", "EDU", "H", "HRB", "LVS", "MAR", "MCD", "NCLH", "PLNT", "PZZA", "SBUX", "TAL", "TXRH", "WEN", "WH", "YUM"],
            "Diversified Financials": ["APAM", "AXP", "BAM", "BEN", "BLK", "BX", "DB", "DFS", "GS", "ICE", "KKR", "LAZ", "MCO", "MS", "OPY", "SEIC", "TROW", "UBS"],
            "Energy": ["AMTX", "BP", "CCJ", "CVX", "ENB", "ET", "HES", "KMI", "NGS", "NOV", "OKE", "PSX", "SUN", "TRP", "XOM"],
            "Food & Staples Retailing": ["CASY", "COST", "SFM", "SYY", "UNFI", "WBA", "WMT"],
            "Food, Beverage & Tobacco": ["DEO", "FIZZ", "GIS", "HSY", "JJSF", "K", "KDP", "KO", "MKC", "MNST", "PEP", "TAP", "THS", "TR", "TSN"],
            "Health Care Equipment & Services": ["ABT", "ACHC", "AMN", "BAX", "CNC", "CVS", "GEG", "GMED", "MCK", "UNH", "VEEV"],
            "Household & Personal Products": ["CL", "EL", "PG", "UL", "WDFC"],
            "Insurance": ["AFL", "ALL", "L", "MET", "PRU"],
            "Materials": ["APD", "ASH", "CHNR", "CLW", "CTVA", "EMN", "FCX", "FMC", "IOSP", "KALU", "KWR", "NTIC", "NTR", "PKX", "RGLD", "X"],
            "Media & Entertainment": ["AMC", "BIDU", "CMCSA", "DIS", "DJCO", "EDR", "GOOG", "IMAX", "MTCH", "NCTY", "NFLX", "NTES", "SIRI", "SOHU", "SPOT"],
            "Pharmaceuticals & Biotechnology": ["ABBV", "AMGN", "BMY", "CPRX", "GILD", "GSK", "HBIO", "ILMN", "JNJ", "MRK", "MYGN", "NVS", "PBH", "PFE", "REGN", "TEVA"],
            "Pharmaceuticals, Biotechnology & Life Sciences": ["GMAB", "IQV"],
            "Real Estate": ["DLR", "DOC", "EXR", "GEO", "IRM", "PSA"],
            "Retailing": ["AEO", "AMZN", "ANF", "AZO", "BABA", "BBW", "BBY", "BNED", "BURL", "DG", "DLTR", "ETSY", "FL", "GRPN", "HD", "KMX", "LE", "LOW", "M", "ORLY", "SFIX", "TCS", "TGT", "TJX", "ULTA", "URBN", "WSM"],
            "Semiconductors & Semiconductor Equipment": ["AMD", "AVGO", "INTC", "NVDA", "NXPI", "QCOM", "TSM", "TXN"],
            "Software & Services": ["ADBE", "BILL", "CRM", "CTSH", "DBX", "DXC", "FICO", "FTNT", "MA", "MANH", "MSFT", "ORCL", "PYPL", "SAP", "SNOW", "V"],
            "Technology Hardware & Equipment": ["AAPL", "ANET", "CSCO", "UTSI", "XRX"],
            "Telecommunication Services": ["GOGO", "RCI", "T", "TU", "VEON", "VZ"],
            "Transportation": ["AAL", "ARCB", "CNI", "CP", "DAL", "HTLD", "JBLU", "LUV", "LYFT", "SAVE", "SKYW", "UBER", "ZTO"],
            "Utilities": ["AEP", "AWK", "D", "FE", "FTS", "MSEX", "NFG", "PCG", "SJW", "SO", "SRE", "UGI", "YORW"]
        };

window.industryColors = {
            "Automobiles & Components": 'rgba(255, 99, 132, 0.3)',
            "Banks": 'rgba(54, 162, 235, 0.4)',
            "Capital Goods": 'rgba(255, 6, 86, 0.5)',
            "Commercial Services & Supplies": 'rgba(75, 192, 192, 0.4)',
            "Consumer Durables & Apparel": 'rgba(153, 102, 255, 0.5)',
            "Consumer Services": 'rgba(25, 159, 64, 0.6)',
            "Diversified Financials": 'rgba(27, 99, 132, 0.4)',
            "Energy": 'rgba(255, 162, 235, 0.5)',
            "Food & Staples Retailing": 'rgba(25, 206, 56, 0.4)',
            "Food, Beverage & Tobacco": 'rgba(75, 192, 192, 0.5)',
            "Health Care Equipment & Services": 'rgba(15, 102, 255, 0.4)',
            "Household & Personal Products": 'rgba(236, 159, 64, 0.4)',
            "Insurance": 'rgba(105, 99, 142, 0.6)',
            "Materials": 'rgba(54, 162, 235, 0.3)',
            "Media & Entertainment": 'rgba(5, 236, 86, 0.4)',
            "Pharmaceuticals & Biotechnology": 'rgba(75, 14, 192, 0.5)',
            "Pharmaceuticals, Biotechnology & Life Sciences": 'rgba(15, 102, 255, 0.4)',
            "Real Estate": 'rgba(25, 159, 64, 0.5)',
            "Retailing": 'rgba(86, 99, 132, 0.4)',
            "Semiconductors & Semiconductor Equipment": 'rgba(54, 162, 235, 0.5)',
            "Software & Services": 'rgba(25, 206, 46, 0.3)',
            "Technology Hardware & Equipment": 'rgba(75, 192, 192, 0.5)',
            "Telecommunication Services": 'rgba(153, 102, 255, 0.4)',
            "Transportation": 'rgba(55, 159, 64, 0.3)',
            "Utilities": 'rgba(165, 99, 132, 0.4)'
        };
